# Generated by Django 3.0.7 on 2020-09-28 10:21

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'record/fixture/prefecture.json', app_label='record')

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
