# Generated by Django 2.2.12 on 2020-05-03 11:20

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.User')),
                ('kana_first_name', models.CharField(max_length=128, verbose_name='姓（かな）')),
                ('kana_last_name', models.CharField(max_length=128, verbose_name='名（かな）')),
                ('department', models.CharField(choices=[('1', '1階'), ('2', '2階'), ('3', '3階'), ('4', '4階'), ('5', '5階'), ('6', '6階')], default='1', max_length=128, verbose_name='部署')),
                ('occupation', models.CharField(choices=[('CS', '介護職'), ('NS', '看護師'), ('Dr', '医師'), ('PT', '理学療法士'), ('OT', '作業療法士'), ('ST', '言語聴覚士')], default='CS', max_length=128, verbose_name='職種')),
                ('reading_comprehension', models.IntegerField(choices=[(0, '必要'), (1, '不要')], verbose_name='日本語サポートの必要性')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('time', models.TimeField(verbose_name='時刻')),
                ('notice', models.CharField(max_length=8000, verbose_name='特記事項')),
                ('translated_notice', models.CharField(max_length=8000, verbose_name='何があったか')),
                ('written_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='名前')),
                ('kana_full_name', models.CharField(max_length=128, verbose_name='フリガナ')),
                ('department', models.CharField(choices=[('1', '1階'), ('2', '2階'), ('3', '3階'), ('4', '4階'), ('5', '5階'), ('6', '6階')], default='1', max_length=128, verbose_name='部署')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('unit', models.CharField(choices=[('E', '東'), ('W', '西')], default='E', max_length=1, verbose_name='ユニット')),
                ('room', models.IntegerField(verbose_name='部屋番号')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_record',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record.Record')),
                ('kind', models.CharField(choices=[('BF', '朝食'), ('LU', '昼食'), ('DI', '夕食')], default='BF', max_length=16, verbose_name='食事の種類')),
                ('staple_food', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='食事量（主食）')),
                ('side_food', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='食事量（副食）')),
            ],
            bases=('record.record',),
        ),
        migrations.AddField(
            model_name='record',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Resident', verbose_name='利用者'),
        ),
        migrations.AddField(
            model_name='record',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='職員'),
        ),
    ]
