# Generated by Django 2.2.12 on 2020-05-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_record',
            name='kind',
            field=models.CharField(choices=[('BF', '朝食'), ('LU', '昼食'), ('DI', '夕食')], default='BF', max_length=16, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='meal_record',
            name='side_food',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='副食量'),
        ),
        migrations.AlterField(
            model_name='meal_record',
            name='staple_food',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, verbose_name='主食量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='notice',
            field=models.CharField(blank=True, max_length=8000, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(default='00:00', verbose_name='時刻'),
        ),
        migrations.AlterField(
            model_name='record',
            name='translated_notice',
            field=models.CharField(blank=True, max_length=8000, verbose_name='何があったか'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='reading_comprehension',
            field=models.IntegerField(choices=[(0, '必要'), (1, '不要')], default=1, verbose_name='日本語サポートの必要性'),
        ),
    ]
