# Generated by Django 2.2.12 on 2020-05-05 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20200505_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='職員'),
        ),
    ]
