# Generated by Django 2.2.12 on 2020-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20200519_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='unit',
            field=models.CharField(max_length=128, verbose_name='ユニット'),
        ),
    ]
