# Generated by Django 2.2.12 on 2020-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_record_istranslated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='isTranslated',
            field=models.BooleanField(default=False, verbose_name='変換済みかどうか'),
        ),
    ]
