# Generated by Django 2.2.12 on 2020-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_auto_20200520_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='notice',
            field=models.CharField(default='', max_length=8000, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='record',
            name='translated_notice',
            field=models.CharField(default='', max_length=8000, verbose_name='変換結果'),
        ),
    ]
