# Generated by Django 2.2.12 on 2020-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_auto_20200522_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_record',
            name='form2',
            field=models.IntegerField(choices=[(0, '10分の0'), (1, '10分の1'), (2, '10分の2'), (3, '10分の3'), (4, '10分の4'), (5, '10分の5'), (6, '10分の6'), (7, '10分の7'), (8, '10分の8'), (9, '10分の9'), (10, '10分の10')], default=10, verbose_name='主食'),
        ),
        migrations.AlterField(
            model_name='meal_record',
            name='form3',
            field=models.IntegerField(choices=[(0, '10分の0'), (1, '10分の1'), (2, '10分の2'), (3, '10分の3'), (4, '10分の4'), (5, '10分の5'), (6, '10分の6'), (7, '10分の7'), (8, '10分の8'), (9, '10分の9'), (10, '10分の10')], default=10, verbose_name='副食'),
        ),
    ]
