# Generated by Django 2.2.12 on 2020-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_auto_20200615_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_record',
            name='form2',
            field=models.IntegerField(choices=[('0/10', '0/10'), ('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10'), ('10/10', '10/10')], default=10, verbose_name='主食量'),
        ),
        migrations.AlterField(
            model_name='meal_record',
            name='form3',
            field=models.IntegerField(choices=[('0/10', '0/10'), ('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10'), ('10/10', '10/10')], default=10, verbose_name='副食量'),
        ),
    ]
