# Generated by Django 2.2.12 on 2020-06-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_auto_20200615_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_record',
            name='form1',
        ),
        migrations.RemoveField(
            model_name='meal_record',
            name='form2',
        ),
        migrations.RemoveField(
            model_name='meal_record',
            name='form3',
        ),
        migrations.AddField(
            model_name='record',
            name='form1',
            field=models.CharField(default='---', max_length=16, verbose_name='項目1'),
        ),
        migrations.AddField(
            model_name='record',
            name='form2',
            field=models.CharField(default='---', max_length=16, verbose_name='項目2'),
        ),
        migrations.AddField(
            model_name='record',
            name='form3',
            field=models.CharField(default='---', max_length=16, verbose_name='項目3'),
        ),
    ]
