# Generated by Django 3.0.7 on 2020-09-26 11:56

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.User')),
                ('full_name', models.CharField(max_length=128, verbose_name='名前')),
                ('kana_full_name', models.CharField(max_length=128, verbose_name='ふりがな')),
                ('department', models.CharField(choices=[('1', '1階'), ('2', '2階'), ('3', '3階'), ('4', '4階'), ('5', '5階'), ('6', '6階')], default='1', max_length=128, verbose_name='部署')),
                ('is_leaving', models.BooleanField(default=False, verbose_name='退所済かどうか')),
                ('occupation', models.CharField(choices=[('CS', '介護職'), ('NS', '看護師'), ('Dr', '医師'), ('PT', '理学療法士'), ('OT', '作業療法士'), ('ST', '言語聴覚士')], default='CS', max_length=128, verbose_name='職種')),
                ('reading_support', models.BooleanField(default=False, verbose_name='日本語サポート')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category_form0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Category_form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='カテゴリ名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Category_form0', verbose_name='親カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Category_form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='カテゴリ名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Category_form0', verbose_name='親カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Category_form3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='カテゴリ名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Category_form0', verbose_name='親カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='名前')),
                ('kana_full_name', models.CharField(max_length=128, verbose_name='ふりがな')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('department', models.CharField(choices=[('1', '1階'), ('2', '2階'), ('3', '3階'), ('4', '4階'), ('5', '5階'), ('6', '6階')], default='1', max_length=128, verbose_name='部署')),
                ('unit', models.CharField(choices=[('東', '東'), ('西', '西')], default='東', max_length=1, verbose_name='ユニット')),
                ('room', models.IntegerField(verbose_name='部屋番号')),
                ('is_leaving', models.BooleanField(default=False, verbose_name='退所済')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(default=0, verbose_name='利用者の部屋番号')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('time', models.TimeField(default='07:00', verbose_name='時刻')),
                ('notice', models.CharField(blank=True, default='', max_length=8000, verbose_name='特記事項')),
                ('translated_notice', models.CharField(blank=True, default='', max_length=8000, verbose_name='変換結果')),
                ('ruby_translated_notice', models.CharField(blank=True, default='', max_length=8000, null=True, verbose_name='変換結果')),
                ('written_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(max_length=128, verbose_name='部署')),
                ('unit', models.CharField(max_length=128, verbose_name='ユニット')),
                ('isTranslated', models.BooleanField(default=False, verbose_name='変換済みかどうか')),
                ('form0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Category_form0', verbose_name='親カテゴリ')),
                ('form1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Category_form1', verbose_name='情報1')),
                ('form2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Category_form2', verbose_name='情報2')),
                ('form3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Category_form3', verbose_name='情報3')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Resident', verbose_name='利用者')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='職員')),
            ],
        ),
    ]
