# Generated by Django 2.2.12 on 2020-07-22 10:39

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.User')),
                ('full_name', models.CharField(max_length=128, verbose_name='名前')),
                ('kana_full_name', models.CharField(max_length=128, verbose_name='ふりがな')),
                ('department', models.CharField(choices=[('1', '1階'), ('2', '2階'), ('3', '3階'), ('4', '4階'), ('5', '5階'), ('6', '6階')], default='1', max_length=128, verbose_name='部署')),
                ('is_leaving', models.BooleanField(default=False, verbose_name='退所済かどうか')),
                ('occupation', models.CharField(choices=[('CS', '介護職'), ('NS', '看護師'), ('Dr', '医師'), ('PT', '理学療法士'), ('OT', '作業療法士'), ('ST', '言語聴覚士')], default='CS', max_length=128, verbose_name='職種')),
                ('reading_support', models.BooleanField(default=False, verbose_name='日本語サポート')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(default=0, verbose_name='利用者の部屋番号')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('time', models.TimeField(default='07:00', verbose_name='時刻')),
                ('notice', models.CharField(blank=True, default='', max_length=8000, verbose_name='特記事項')),
                ('translated_notice', models.CharField(blank=True, default='', max_length=8000, verbose_name='変換結果')),
                ('written_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(max_length=128, verbose_name='部署')),
                ('unit', models.CharField(max_length=128, verbose_name='ユニット')),
                ('isTranslated', models.BooleanField(default=False, verbose_name='変換済みかどうか')),
                ('is_leaving', models.BooleanField(default=False, verbose_name='退所済かどうか')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='名前')),
                ('kana_full_name', models.CharField(max_length=128, verbose_name='ふりがな')),
                ('department', models.CharField(choices=[('1', '1階'), ('2', '2階'), ('3', '3階'), ('4', '4階'), ('5', '5階'), ('6', '6階')], default='1', max_length=128, verbose_name='部署')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('unit', models.CharField(choices=[('東', '東'), ('西', '西')], default='東', max_length=1, verbose_name='ユニット')),
                ('room', models.IntegerField(verbose_name='部屋番号')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_record',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record.Record')),
                ('form1', models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食')], default='朝食', max_length=16, verbose_name='種類')),
                ('form2', models.CharField(choices=[(' 0/10', ' 0/10'), (' 1/10', ' 1/10'), (' 2/10', ' 2/10'), (' 3/10', ' 3/10'), (' 4/10', ' 4/10'), (' 5/10', ' 5/10'), (' 6/10', ' 6/10'), (' 7/10', ' 7/10'), (' 8/10', ' 8/10'), (' 9/10', ' 9/10'), ('10/10', '10/10')], default='10/10', max_length=16, verbose_name='主食量')),
                ('form3', models.CharField(choices=[(' 0/10', ' 0/10'), (' 1/10', ' 1/10'), (' 2/10', ' 2/10'), (' 3/10', ' 3/10'), (' 4/10', ' 4/10'), (' 5/10', ' 5/10'), (' 6/10', ' 6/10'), (' 7/10', ' 7/10'), (' 8/10', ' 8/10'), (' 9/10', ' 9/10'), ('10/10', '10/10')], default='10/10', max_length=16, verbose_name='副食量')),
            ],
            bases=('record.record',),
        ),
        migrations.AddField(
            model_name='record',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Resident', verbose_name='利用者'),
        ),
        migrations.AddField(
            model_name='record',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='職員'),
        ),
    ]
