# Generated by Django 2.2.12 on 2020-04-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='kana_full_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='kana_first_name',
            field=models.CharField(default=1, max_length=128, verbose_name='姓（かな）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='kana_last_name',
            field=models.CharField(default=1, max_length=128, verbose_name='名（かな）'),
            preserve_default=False,
        ),
    ]
