# Generated by Django 2.2.12 on 2020-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_leaving',
            field=models.BooleanField(default=False, verbose_name='退所済かどうか'),
        ),
    ]
