# Generated by Django 3.0.7 on 2020-09-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_form0',
            name='form1_name',
            field=models.CharField(default='', max_length=50, verbose_name='情報1の項目名'),
        ),
        migrations.AddField(
            model_name='category_form0',
            name='form2_name',
            field=models.CharField(default='', max_length=50, verbose_name='情報2の項目名'),
        ),
        migrations.AddField(
            model_name='category_form0',
            name='form3_name',
            field=models.CharField(default='', max_length=50, verbose_name='情報3の項目名'),
        ),
        migrations.AddField(
            model_name='category_form1',
            name='label',
            field=models.CharField(default='', max_length=50, verbose_name='カテゴリ名'),
        ),
    ]
