# Generated by Django 2.2.12 on 2020-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200615_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='form1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='form2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='form3',
        ),
        migrations.AddField(
            model_name='meal_record',
            name='form1',
            field=models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食')], default='朝食', max_length=16, verbose_name='種類'),
        ),
        migrations.AddField(
            model_name='meal_record',
            name='form2',
            field=models.CharField(choices=[(' 0/10', ' 0/10'), (' 1/10', ' 1/10'), (' 2/10', ' 2/10'), (' 3/10', ' 3/10'), (' 4/10', ' 4/10'), (' 5/10', ' 5/10'), (' 6/10', ' 6/10'), (' 7/10', ' 7/10'), (' 8/10', ' 8/10'), (' 9/10', ' 9/10'), ('10/10', '10/10')], default='10/10', max_length=16, verbose_name='主食量'),
        ),
        migrations.AddField(
            model_name='meal_record',
            name='form3',
            field=models.CharField(choices=[(' 0/10', ' 0/10'), (' 1/10', ' 1/10'), (' 2/10', ' 2/10'), (' 3/10', ' 3/10'), (' 4/10', ' 4/10'), (' 5/10', ' 5/10'), (' 6/10', ' 6/10'), (' 7/10', ' 7/10'), (' 8/10', ' 8/10'), (' 9/10', ' 9/10'), ('10/10', '10/10')], default='10/10', max_length=16, verbose_name='副食量'),
        ),
    ]
