# Generated by Django 2.2.12 on 2020-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_resident_is_leaving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_leaving',
        ),
        migrations.AlterField(
            model_name='resident',
            name='is_leaving',
            field=models.BooleanField(default=False, verbose_name='退所済'),
        ),
    ]
