# Generated by Django 3.0.7 on 2020-09-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20200926_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_terms_noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.CharField(max_length=1000, verbose_name='変換後（名詞）')),
                ('necessity_of_translate', models.BooleanField(default=True, verbose_name='変換する(offの場合は解説として表示)')),
            ],
        ),
        migrations.AlterField(
            model_name='category_form0',
            name='form1_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='情報1の項目名'),
        ),
        migrations.AlterField(
            model_name='category_form0',
            name='form2_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='情報2の項目名'),
        ),
        migrations.AlterField(
            model_name='category_form0',
            name='form3_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='情報3の項目名'),
        ),
        migrations.AlterField(
            model_name='category_form1',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目名(あとから自動入力)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='form0',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='record.Category_form0', verbose_name='親カテゴリ'),
            preserve_default=False,
        ),
    ]
