# Generated by Django 2.2.12 on 2020-06-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20200615_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_leaving',
            field=models.BooleanField(default=False, verbose_name='退所済かどうか'),
        ),
    ]
