# Generated by Django 3.0.7 on 2020-08-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_record_ruby_translated_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ruby_translated_notice',
            field=models.CharField(blank=True, default='', max_length=8000, null=True, verbose_name='変換結果'),
        ),
    ]
