# Generated by Django 3.0.7 on 2020-09-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20200928_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technical_terms_noun',
            new_name='Technical_noun',
        ),
    ]
