# Generated by Django 3.0.7 on 2020-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20200820_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='form0',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='介助の種類'),
        ),
        migrations.AddField(
            model_name='record',
            name='form1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='情報1'),
        ),
        migrations.AddField(
            model_name='record',
            name='form2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='情報2'),
        ),
        migrations.AddField(
            model_name='record',
            name='form3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='情報3'),
        ),
        migrations.DeleteModel(
            name='Meal_record',
        ),
    ]
