# Generated by Django 2.2.12 on 2020-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20200505_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='department',
            field=models.CharField(default=1, max_length=128, verbose_name='部署'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='unit',
            field=models.CharField(default='E', max_length=128, verbose_name='ユニット'),
        ),
    ]
