# Generated by Django 2.2.12 on 2020-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_staff_is_leaving'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='room',
            field=models.IntegerField(default=0, verbose_name='利用者の部屋番号'),
        ),
    ]
