# Generated by Django 3.0.7 on 2020-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20200827_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='form0',
            field=models.CharField(blank=True, choices=[('食事', '食事'), ('入浴', '入浴'), ('生活', '生活'), ('医療', '医療'), ('夜間', '夜間'), ('リハビリ', 'リハビリ'), ('家族連絡', '家族連絡'), ('事故', '事故'), ('その他', 'その他')], max_length=50, null=True, verbose_name='介助の種類'),
        ),
    ]
