# Generated by Django 2.2.12 on 2020-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_record_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='reading_comprehension',
        ),
        migrations.AddField(
            model_name='staff',
            name='reading_support',
            field=models.BooleanField(default=False, verbose_name='日本語サポート'),
        ),
    ]
