# Generated by Django 2.2.12 on 2020-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20200519_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='isTranslated',
            field=models.BooleanField(default=False),
        ),
    ]
