# Generated by Django 3.0.7 on 2020-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_auto_20200831_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='form1',
            field=models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50, null=True, verbose_name='情報1'),
        ),
        migrations.AlterField(
            model_name='record',
            name='form2',
            field=models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50, null=True, verbose_name='情報2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='form3',
            field=models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50, null=True, verbose_name='情報3'),
        ),
    ]
