# Generated by Django 2.2.12 on 2020-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20200519_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='reading_comprehension',
            field=models.IntegerField(choices=[(0, '不要'), (1, '必要')], default=1, verbose_name='日本語サポートの必要性'),
        ),
    ]
