# Generated by Django 2.2.12 on 2020-05-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20200520_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_record',
            old_name='kind',
            new_name='form1',
        ),
        migrations.RenameField(
            model_name='meal_record',
            old_name='staple_food',
            new_name='form2',
        ),
        migrations.RenameField(
            model_name='meal_record',
            old_name='side_food',
            new_name='form3',
        ),
        migrations.AlterField(
            model_name='resident',
            name='kana_full_name',
            field=models.CharField(max_length=128, verbose_name='ふりがな'),
        ),
    ]
