# Generated by Django 2.2.12 on 2020-05-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_auto_20200520_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_record',
            name='form1',
            field=models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食')], default='BF', max_length=16, verbose_name='種類'),
        ),
    ]
