# Generated by Django 2.2.12 on 2020-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_auto_20200522_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_record',
            name='form2',
            field=models.IntegerField(choices=[(0, '0分目'), (1, '1分目'), (2, '2分目'), (3, '3分目'), (4, '4分目'), (5, '5分目'), (6, '6分目'), (7, '7分目'), (8, '8分目'), (9, '9分目'), (10, '10分目')], default=10, verbose_name='主食'),
        ),
        migrations.AlterField(
            model_name='meal_record',
            name='form3',
            field=models.IntegerField(choices=[(0, '0分目'), (1, '1分目'), (2, '2分目'), (3, '3分目'), (4, '4分目'), (5, '5分目'), (6, '6分目'), (7, '7分目'), (8, '8分目'), (9, '9分目'), (10, '10分目')], default=10, verbose_name='副食'),
        ),
        migrations.AlterField(
            model_name='record',
            name='notice',
            field=models.CharField(blank=True, default='', max_length=8000, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='record',
            name='translated_notice',
            field=models.CharField(blank=True, default='', max_length=8000, verbose_name='変換結果'),
        ),
    ]
